MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT

resources/assets/js/components/affiliate/Add.vue, resources/assets/js/components/affiliate/Fingerprint.vue, resources/assets/js/components/affiliate/List.vue, resources/assets/js/components/affiliate/PoliceData.vue, resources/assets/js/components/affiliate/Spouse.vue, routes/api.php
=> Formatted dates as locale and added permissions to police data and spouse components

database/migrations/2019_11_29_113206_crear_loan_requests_table.php
Creacion de tabla loan_requests
=> migrate table loan_requests

app/Http/Controllers/Api/V1/LoanController.php, app/Http/Controllers/Api/V1/LoanRequestController.php, resources/views/prerequest.blade.php, resources/views/request.blade.php, routes/api.php, webpack.mix.js
Formulario pre_solicitud modificado
=> Formato PDF pre_request modificado

resources/assets/js/components/workflow/Add.vue, resources/assets/js/components/workflow/Dashboard.vue
=> visualizar datos de conyugue en datos del prestamo 

app/Loan.php, resources/views/loan/contracts/hypothecary.blade.php, resources/views/loan/contracts/long.blade.php, resources/views/loan/contracts/short.blade.php
Revisión del método para evaluar la sub modalidad (caso refinanciamiento), se modifico la clase Loan.php y el metodo get_modality
=> Revisión del método para evaluar la sub modalidad (caso Refinanciamiento)

database/migrations/2020_10_23_083301_create_sismu_table.php
Creación de la tabla "sismu" para el almacenado de datos del Sistema SISMU
=> Creacion de la tabla "sismu" para el almacenado de datos del Sistema SISMU

app/Loan.php
Modificación del método para obtener la sub modalidad
=> modificacion metodo para obtener la sub modalidad del afiliado

app/Http/Controllers/Api/V1/AffiliateController.php, app/Loan.php, routes/api.php
modificación  para obtener modalidad del afiliado por POST
=> modificacion  para obtener modalidad del afiliado por POST

resources/views/loan/contracts/hypothecary.blade.php, resources/views/loan/contracts/long.blade.php, resources/views/loan/contracts/short.blade.php
Modificacion de contratos de Refinanciamiento Caso SISMU
=> Modificacion de contratos de Refinanciamiento Caso SISMU

database/seeds/LoanStructureSeeder.php, resources/views/loan/contracts/hypothecary.blade.php, resources/views/loan/contracts/long.blade.php, storage/responses/affiliate/get_loan_modality.200.json
Uniformar y modificacion de nombres de las sub modalidades de Refinanciamiento
=> Uniformar y modificacion de nombres de las sub modalidades de Refinanciamiento

app/Http/Controllers/Api/V1/AffiliateController.php, app/Loan.php, database/seeds/LoanStructureSeeder.php, resources/views/loan/contracts/hypothecary.blade.php, resources/views/loan/contracts/long.blade.php
Modificacion del metoto get modality caso de reprogramacion PVT y SISMU
=> Modificacion del metoto get modality caso de reprogramacion PVT y SISMU 

app/Http/Requests/AffiliateForm.php, app/Loan.php
obtención de  mod reprogramación
=> obtencion de  mod reprogramacion 

app/Http/Controllers/Api/V1/AffiliateController.php, app/Http/Requests/AffiliateForm.php
Se agrego la validación a la obtención de modalidad
=> Se agrego la validación a la obtención de modalidad

app/Loan.php
correccion metodo get_modalities bug
=> correccion metodo get_modalities bug

app/Http/Controllers/Api/V1/PersonalReferenceController.php, app/Http/Requests/PersonalReferenceForm.php, database/migrations/2019_10_31_084036_create_personal_reference_table.php
Validación de datos del Personal de Referencia
=> Validacion de datos del Personal de Referencia 

resources/assets/js/components/loan/Requirement.vue
=> closed #1144

app/Loan.php
ajustes método modalidades, considerando los financiamientos de los re financiamiento y evaluación del método para caso CPOP
=> ajustes metodo modalidades

app/Loan.php
obtener  modalidad Cpop  caso refi y repro
=> obtener  modalidad Cpop  caso refi y repro

app/Http/Requests/LoanForm.php
Validación de datos requeridos  para refi y repro
=> Validación de datos requeridos  para refi

app/Http/Controllers/Api/V1/AffiliateController.php
mensaje de afiliado no califica con modalidaa
=> mensaje de afiliado no califica con modalidaa

app/Loan.php
=> ajuste modalities

app/Http/Controllers/Api/V1/AffiliateController.php, app/Loan.php
=> ajuste modalidades afili

app/Http/Controllers/Api/V1/LoanController.php
corrección validación de dirección requerido
=> corrección validación de dirección requerido

app/Http/Requests/AffiliateForm.php, app/Loan.php
Validacion del campo requerido para pasivo del ente gestor y obtencion de modlidad de afp del campo pension_entity
=> Validacion del campo requerido para pasivo del ente gestor y obtencion de modlidad de afp del campo pension_entity

app/Http/Requests/LoanForm.php
=> Correccion loan form

app/Http/Requests/LoanPaymentForm.php
=> Correccion de loanPayment

app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Imports/LoanPaymentImport.php, routes/api.php
Importacion de datos de Comando y Senasir
=> Importacion de datos de Comando y Senasir

app/Http/Controllers/Api/V1/LoanPaymentController.php, storage/responses/loan_payment/importation_payments.200.json
documentacion importation loan payment
=> documentacion importation loan payment

app/Http/Controllers/Api/V1/LoanPaymentController.php
ajuste correccion metodo importacion Comand Senasir
=> ajuste correccion metodo importacion Comand Senasir

app/Http/Controllers/Api/V1/LoanController.php, app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Http/Requests/LoanForm.php, app/Loan.php, routes/api.php
Reporte xls de prestamos en mora y bug de actualizacion de desembolso de prestamo
=> Reporte xls de prestamos en mora y bug de actualizacion de desembolso de prestamo 

app/Http/Requests/LoanForm.php
correccion de bug al actualizar el la fecha de desembolso
=> correccion de bug al actualizar el la fecha de desembolso

app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Loan.php
Prestamos en mora los dias de penal, modificacion metodo
=> Prestamos en mora los dias de penal, modificacion metodo

database/migrations/2019_09_23_161220_create_records_table.php, database/migrations/2021_02_09_134206_add_role_to_records.php
modificacion de las migracion records
=> modificacion de las migracion records

app/Helpers/Util.php, app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Http/Controllers/Api/V1/StatisticController.php, app/LoanPayment.php, resources/views/loan/payments/payment_plan.blade.php
añadido la ultima corrección del plan de pagos
=> Estaditsico y filtrado de plan de pagos

app/Helpers/Util.php, app/Http/Controllers/Api/V1/LoanController.php, app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Http/Controllers/Api/V1/VoucherController.php, composer.json, config/app.php, resources/views/partials/footer.blade.php
Libreria QR y adicion de informacion en el pie de pagina en los contratos
=> libreria QR y adicion de informacion en el pie de pagina en los contratos

resources/views/loan/payments/payment_kardex.blade.php
modificación de la impresión del kardex cliente
=> modificación de la impresion del kardex cliente

app/Loan.php, resources/views/loan/payments/payment_plan.blade.php
Adicionar informacion plan de pagos con codeudores
=> Adicionar informacion plan de pagos con codeudores y modificacion de next payment para el calculo del cobro 

app/Http/Controllers/Api/V1/StatisticController.php, app/Loan.php, app/LoanPayment.php
Correccion de calculos next payment
=> Correccion de calculos next payment

resources/views/loan/payments/payment_loan.blade.php
Modificación de pdf para impresión del registro de cobro
=> modificación de pdf para impresión del registro de cobro

app/LoanPayment.php
Correccion LoanPaymet relacion User
=> Correccion LoanPaymet relacion User

app/Http/Controllers/Api/V1/LoanController.php, storage/responses/loan/set_payment.200.json
adicion de usuario al guardar nuevo registro de pago
=> adicion de usuario al guardar nuevo registro de pago

database/seeds/AdvanceRoleSeeder.php, database/seeds/LoanStateSeeder.php, database/seeds/RoleSequenceSeeder.php
Creación de flujo para el área de cobranza
=> Creación de flujo para el área de cobranza

app/Http/Controllers/Api/V1/LoanPaymentController.php, app/LoanPayment.php
modificacion de metodos index y registr payment exportacion
=> modificacion de metodos index y registr payment(exportacion)

app/Http/Controllers/Api/V1/LoanPaymentController.php
Modificacion del metodo set_voucher adicion de usuario -  flujos
=> Modificacion del metodo set_voucher adicion de usuario -  flujos

database/seeds/AdvanceRoleSeeder.php
Se agrega permisos al rol tesorería cobros AdvanceRoleSeeder.php
=> Se agrega permisos al rol tesorería cobros AdvanceRoleSeeder.php

app/Http/Controllers/Api/V1/LoanController.php
Ajuste set_payment usuario si se envia o no el usuario
=> Ajuste set_payment usuario si se envia o no el usuario

app/AidContribution.php, app/Http/Controllers/Api/V1/AffiliateController.php, storage/responses/affiliate/get_contributions.200.json
Adicion metodo contribuciones adicionando logica para loa pasivos
=> Adicion metodo contribuciones adicionando logica para loa pasivos

resources/views/flow/bulk_flow_procedures.blade.php, resources/views/flow/tbody/loan_payment.blade.php, resources/views/flow/thead/loan_payment.blade.php
Adicion de informacion de registro de cobro en la derivacion
=> Adicion de informacion de registro de cobro en el comprobante de derivacion

database/migrations/2021_03_04_091046_create_loan_contribution_adjusts_table.php, resources/views/loan/payments/payment_loan.blade.php
Creación de la tabla loan_contribution_adjusts
=> Creación de la tabla loan_contribution_adjusts

app/Affiliate.php, app/Http/Controllers/Api/V1/AffiliateController.php
contribuciones pasivos activos e item 0
=> contribuciones pasivos activos e item 0 

app/AidContribution.php, app/Http/Controllers/Api/V1/AidContributionController.php, app/Http/Requests/AidContributionForm.php, routes/api.php, storage/responses/aid_contribution/destroy.200.json, storage/responses/aid_contribution/index.200.json, storage/responses/aid_contribution/show.200.json, storage/responses/aid_contribution/store.200.json, storage/responses/aid_contribution/update.200.json, storage/responses/aid_contribution/updateOrCreate.200.json
CRUD Aid_contributions Form y metodo de updateOrCreate y documentacion
=> CRUD Aid_contributions Form y metodo de updateOrCreate y documentacion

app/Affiliate.php
creación del método de validación para garante fallecido y pasivo SENASIR verify_guarantor
=> creación del método de validación para garante verify_guarantor

app/Http/Controllers/Api/V1/AffiliateController.php, storage/responses/affiliate/get_contributions.200.json
Contribution adicion para Datos para item 0
=> Contribution adicion para Datos para item 0

app/Http/Controllers/Api/V1/AffiliateController.php, app/Http/Controllers/Api/V1/LoanController.php, storage/responses/affiliate/get_contributions.200.json
Adicion de datos en el metodo contribution
=> Adicion de datos en el metodo contribution

app/Http/Controllers/Api/V1/LoanContributionAdjustController.php, app/Http/Requests/LoanContributionAdjustForm.php
modificación de la validación y adición del usuario en el registro de la tabla loanContrbutonAdjus
=>  modificación de la validación y adición del usuario en el registro de la tabla loanContrbutonAdjus

app/Http/Controllers/Api/V1/AffiliateController.php
arreglo de validacion boolean en contributions
=> arreglo de validacion boolean en contributions 

routes/api.php, storage/responses/aid_contribution/index.200.json
=> Correccion ortografico

app/Http/Controllers/Api/V1/CalculatorController.php
correccion de Calculos del liquido para calificacion
=> correccion de Calculos del liquido para calificacion

app/Http/Controllers/Api/V1/LoanController.php, app/Loan.php
Creación del método para recuperación de datos de la boleta de acuerdo al préstamo
=> Creación del método para recuperación de datos de la boleta

app/Http/Controllers/Api/V1/LoanController.php, app/Http/Requests/LoanForm.php, app/Observers/LoanObserver.php, storage/responses/calculator/store.200.json
Metodos para rehacer el prestamo
=> Metodos para rehacer el prestamo

app/AidContribution.php, app/Observers/AidContributionObserver.php, app/Providers/AidContributionServiceProvider.php, app/Providers/AppServiceProvider.php, app/Record.php, config/app.php, config/translations.php, database/seeds/RecordTypeNameSeeder.php
Observadores tabla aid contributions
=> Observadores tabla aid contributions

app/Http/Controllers/Api/V1/LoanController.php, app/Http/Requests/LoanForm.php
**adicion de validacion de remake_loan_id cuando se envia 0**
=> adicion de validacion de remake_loan_id cuando se envia 0

app/Http/Controllers/Api/V1/CalculatorController.php
=> Correccion calculo liq

app/Http/Controllers/Api/V1/LoanContributionAdjustController.php, routes/api.php, storage/responses/loan_contribution_adjust/show.200.json
Método para realizar Búsqueda de un registro del ajuste de una contribución por el ID
=> Metodo para realizar Busqueda de un registro del ajuste de una contribucion por el ID

app/Http/Controllers/Api/V1/AffiliateController.php
adicion de current tiket todas las modalidades metodo contributions
=> adicion de current tiket todas las modalidades metodo contributions 

app/Address.php, app/Http/Requests/LoanForm.php, database/migrations/2019_10_21_112920_add_geolocation_to_addresses_table.php, database/migrations/2019_10_21_121445_modify_for_cascade_delete_on_addressables_table.php, database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php, database/seeds/LoanGlobalParameterSeeder.php, storage/responses/loan_global_parameter/show.200.json
Validacion loan y creacion de campos para direcciones y global parameter
=> Validacion loan y creacion de campos para direcciones y global parameter

app/LoanContributionAdjust.php, app/Observers/LoanContributionAdjustObserver.php, app/Providers/AppServiceProvider.php, app/Providers/LoanContributionAdjustModelServiceProvider.php, app/Record.php, config/app.php, database/seeds/RecordTypeNameSeeder.php
Creación de Observers a la tabla LoanContributionAdjust que se registrara en la tabla récords
=> creacion de observers en el record de LoanCotributionAdjust

app/Http/Controllers/Api/V1/LoanController.php, resources/views/loan/forms/qualification_form.blade.php, routes/api.php
Ajuste del formulario de calificación para añadir afiliado en comisión
=> Ajuste del formulario de calificación para añadir afiliado en comisión

app/Http/Controllers/Api/V1/AffiliateController.php
=> Ajuste de contrbuciones

app/Http/Controllers/Api/V1/LoanController.php
colocar el codigo del remake sin actualizar
=> colocar el codigo del remake sin actualizar

app/Http/Controllers/Api/V1/LoanController.php, app/Loan.php, storage/responses/loan/loan_evaluate.200.json
Verificar los pagos manuales consecutivos de un prestamo
=> Verificar los pagos manuales consecutivos de un prestamo 

app/Http/Controllers/Api/V1/AffiliateController.php
=> Modificacion numero de meses

database/seeds/LoanStructureSeeder.php
=> seeder hipotecario 3 ballots

app/Http/Controllers/Api/V1/LoanController.php, app/Observers/LoanObserver.php, database/seeds/AdvanceRoleSeeder.php, database/seeds/TagSeeder.php
Etiqueta sismu, y correccion de etiqueas, silenciar onservador evento
=> Etiqueta sismu, y correccion de etiqueas, silenciar onservador evento

database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php, database/seeds/LoanGlobalParameterSeeder.php
agrego parametros globales para refi
=> agrego parametros globales para refi 

app/Address.php, app/Http/Controllers/Api/V1/AddressController.php
Ajuste de direccion en el guardado
=> Ajuste de direccion en el guardado

resources/views/loan/forms/qualification_form.blade.php
Se agrega promedio de bonos y liquido  al formulario de calificación
=> Se agrega promedio de bonos y liquido  al formulario de calificación

app/Address.php, app/Affiliate.php, app/Http/Controllers/Api/V1/AffiliateController.php, app/Loan.php, routes/api.php, storage/responses/affiliate/affiliate_evaluate_loans.200.json
Busqueda de modalidad de prestamos para el affiliado segun ci
=> Busqueda de modalidad de prestamos para el affiliado segun ci

database/seeds/LoanDestinyProcedureTypeSeeder.php, database/seeds/LoanDestinySeeder.php, version-seeder.sh
Creación del seeder LoanDestinyProcedureTypeSeeder para la asignación de destinos de un préstamo
=> Creación del seeder LoanDestinyProcedureTypeSeeder

app/Http/Controllers/Api/V1/AffiliateController.php, app/PersonalReference.php, resources/views/loan/contracts/hypothecary.blade.php
Cambio de campo de description a zone
=> Cambio de campo de description a zone temporal

app/Http/Controllers/Api/V1/AffiliateController.php, storage/responses/affiliate/affiliate_evaluate_loans.200.json
Se agrego validation de ci a metodo seach loan
=> Se agrego validacion de ci a metodo seach loan

app/Http/Controllers/Api/V1/LoanController.php, routes/api.php, storage/responses/loan/affiliate_evaluate.200.json
Creación del método validate_affiliate para la validación de que el afiliado tenga actualizado su documentación para realizar un préstamo
=> Creación del método validate_affiliate 

app/Http/Controllers/Api/V1/LoanController.php
ajuste del método de validate_affiliate
=> ajuste del método de validate_affiliate

app/Http/Controllers/Api/V1/LoanController.php, database/seeds/CityGeolocationSeeder.php, database/seeds/ProcedureAmortizationSeeder.php, database/seeds/RoleSequenceSeeder.php, storage/responses/loan_payment/bullk_update_role.200.json, storage/responses/procedure_type/get_modality.200.json, storage/responses/procedure_type/show.200.json
=> Submodalidades amortizaciones

app/Address.php
=> mostrar la descripcion en la zona en los contratos

app/Http/Controllers/Api/V1/AffiliateController.php, app/Loan.php
=> modificacion de metodos 

app/Loan.php
adicion del objeto de modalidad con el nombre
=> adicion del objeto de modalidad con el nombre

app/Http/Controllers/Api/V1/AffiliateController.php, app/Http/Controllers/Api/V1/LoanController.php, storage/responses/affiliate/get_loan_modality.200.json, storage/responses/affiliate/get_loans.200.json
Adicion de informacion en el apend data y actualizacion de documentacion
=> Adicion de informacion en el apend data y actualizacion de documentacion

app/Http/Controllers/Api/V1/LoanController.php, routes/api.php, storage/responses/affiliate/get_loans.200.json, storage/responses/loan/get_procedure_relation.200.json
Metodo para la relcion de procedures hermanos y documentacion y loan append data
=> Metodo para la relcion de procedures hermanos y documentacion y loan append data

app/Http/Controllers/Api/V1/LoanController.php, app/Loan.php
modificacion del metodo para obtener la modalidad
=> modificacion del metodo para obtener la modalidad

app/Http/Controllers/Api/V1/AffiliateController.php
Ajuste al metodo de obtencion de contribuciones
=> Ajuste al metodo de obtencion de contribuciones

app/Helpers/Util.php, app/Http/Controllers/Api/V1/LoanController.php, app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Http/Controllers/Api/V1/ModuleController.php, app/Module.php, app/RoleSequence.php
Modificación de los métodos de flujos de trabajo para las diferentes
=> Modificación de los métodos de flujos de trabajo para las diferentes

app/Http/Controllers/Api/V1/LoanController.php, app/Loan.php, database/migrations/2019_10_31_084035_create_loans_table.php, database/seeds/LoanStructureSeeder.php
Reprogramacion modificaciones de como procedure
=> Reprogramacion modificaciones de como procedure

app/Http/Controllers/Api/V1/LoanController.php, app/Http/Requests/LoanForm.php, app/Loan.php, storage/responses/affiliate/get_loans.200.json, storage/responses/loan/update.200.json
CReacion de campo para verificar si la amortizacion es de garante
=> CReacion de campo para verificar si la amortizacion es de garante

app/Http/Requests/LoanForm.php
=> modificacion de validacion

app/Http/Controllers/Api/V1/LoanController.php, app/Loan.php, database/seeds/LoanDestinyProcedureTypeSeeder.php, database/seeds/LoanStructureSeeder.php, resources/assets/js/components/loan/Ballots.vue, resources/assets/js/components/loan/Steps.vue
Sedder destinos de prestamos refinanciandos y cor ortog
=> Sedder destinos de prestamos refinanciandos y cor ortog

app/Loan.php
validacion para hipotecario de afiliado con item 0
=> validacion para hipotecario de afiliado con item 0

database/seeds/AdvanceRoleSeeder.php, database/seeds/RoleSequenceSeeder.php
cargar en el seeder flujo de trabajo con el nueva secuencia creada sequence_number_flow
=> cargar en el seeder flujo de trabajo con el nueva secuencia creada sequence_number_flow

app/Affiliate.php, app/Http/Controllers/Api/V1/LoanController.php, storage/responses/loan/show.200.json
Método para verificar si el afiliado tiene contribuciones y enviar los tags al detalle del préstamo
=> Método para verificar si el afiliado tiene contribuciones y enviar los tags al detalle del préstamo

app/Http/Controllers/Api/V1/ProcedureTypeController.php, database/seeds/RoleSequenceSeeder.php
Validación de flujo de trabajo
=> Validación de flujo de trabajo

app/Http/Controllers/Api/V1/LoanController.php, storage/responses/loan/show.200.json
Recuperar datos del padre y devolver el second name
=> Recuperar datos del padre y devolver el second name

app/Http/Controllers/Api/V1/AffiliateController.php, app/Loan.php
Agregar en la obtencion de modalidad si es cpop
=> Agregar en la obtencion de modalidad si es cpop

app/Affiliate.php, app/Http/Controllers/Api/V1/ProcedureTypeController.php
Realizar validación para que un usuario en comisión no pueda ser garante
=> validacion para que usuario comision no pueda ser garante

app/Http/Controllers/Api/V1/LoanController.php
Llamar al parent loan en el detalle del prestamo
=> Llamar al parent loan en el detalle del prestamo

app/Http/Controllers/Api/V1/LoanController.php, storage/responses/loan/show.200.json
Adicion de datos del parent loan en el detalle
=> Adicion de datos del parent loan en el detalle

app/Http/Controllers/Api/V1/LoanPaymentController.php
Validar en print_loan_payment no sume saldo anterior cobros anulados
=> Validar en print_loan_payment no sume saldo anterior cobros anulados

app/Loan.php
quitar modalidad de cpop sector pasivos
=> quitar modalidad de cpop sector pasivos

app/Loan.php
Adcion de casos para cobros sub
=> Adcion de casos para cobros sub

app/Helpers/Util.php
Correccion de devolucion de procedures, rspuesta demorada
=> Correccion de devolucion de procedures, rspuesta demorada

app/Http/Controllers/Api/V1/LoanPaymentController.php
amortizacion cambiar a pagabdo ala actualizar
=> amortizacion cambiar a pagabdo ala actualizar

app/Http/Controllers/Api/V1/LoanPaymentController.php
arreglo de edicion de pago cobranzas
=> arreglo de edicion de pago cobranzas

app/Http/Controllers/Api/V1/RecordController.php, routes/api.php, storage/responses/record/get_record_loan_payment.200.json
método para obtener el filtrado del historial de cobro
=> Método para obtener el filtrado del historial de cobro

app/Http/Controllers/Api/V1/LoanPaymentController.php, storage/responses/loan_payment/show.200.json
LoanPAyment añadir mas info al detalle y adicon de documentacion
=> LoanPayment añadir mas info al detalle y adicon de documentacion

app/Http/Requests/LoanForm.php
validación Refinanciamiento Préstamo hipotecario
=> validacion Refinanciamiento Préstamo hipotecario

app/Http/Controllers/Api/V1/LoanPaymentController.php
se adiciona estado al método indexKardex
=> se adiciona estado al método indexKardex

app/Http/Controllers/Api/V1/LoanPaymentController.php
ajuste detalle del estado de un estado de pago
=> ajuste detalle del estado de un estado de pago 

app/Http/Controllers/Api/V1/LoanPaymentController.php
Ajuste de eliminar pagos en estado pendiente y actualizar estado
=> Ajuste de eliminar pagos en estado pendiente y actualizar estado 

app/Http/Controllers/Api/V1/LoanPaymentController.php
ajuste de print_loan_payment para imprimir formulario
=> ajuste de print_loan_payment para imprimir formulario

app/Http/Controllers/Api/V1/LoanController.php, app/Http/Requests/AffiliateForm.php
Quitar la validación de requerido la ciudad de expedición del carnet
=> Quitar la validación de requerido la ciudad de expedición del carnet

app/Http/Controllers/Api/V1/LoanController.php
ajuste de validación del ente gestor
=> ajuste de validación del ente gestor

app/Http/Controllers/Api/V1/LoanController.php, config/translations.php, storage/responses/loan/show.200.json
Adicionar informacion del prestamo para mostrar datos a cobranzas
=> Adicionar informacion del prestamo para mostrar datos a cobranzas 

app/Affiliate.php, app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Loan.php, database/seeds/LoanStateSeeder.php, database/seeds/ProcedureAmortizationSeeder.php, storage/responses/loan_payment/show.200.json
Seeder de submodalidades de amortizaciones y cambio de estado
=> Seeder de submodalidades de amortizaciones y cambio de estado

database/seeds/LoanStructureSeeder.php
Arreglo seeder hipotecario cpop
=> Arreglo seeder hipotecario cpop

app/Http/Controllers/Api/V1/AffiliateController.php
Quitar validadcion del registro de la direccion
=> Quitar validadcion del registro de la direccion

app/Http/Controllers/Api/V1/AffiliateController.php
=> Arreglo bug Affiliate

app/Loan.php
Bug de obtencion de modalidad del largo plazo sector pasivo
=> Bug de obtencion de modalidad del largo plazo sector pasivo 

resources/views/loan/forms/qualification_form.blade.php
Agregar datos de evaluación del garante en formulario de Calificación
=> Agregar datos de evaluación del garante en formulario de Calificación

app/Http/Controllers/Api/V1/LoanPaymentController.php, app/LoanPayment.php
Amortización por prioridades en la importación Caso garantes y titulares
=> Amortización por prioridades en la importación Caso garantes y titulares 

app/Http/Controllers/Api/V1/LoanPaymentController.php, resources/views/loan/payments/payment_loan.blade.php
Modificar print_loan_payment.php y payment_loan.blade para agregar viudas como garante
=> Modificar print_loan_payment.php y payment_loan.blade para agregar viudas como garante

app/Affiliate.php
=> bug verify_guarantor

app/LoanModalityParameter.php, database/migrations/2019_11_29_112944_create_loan_modality_parameters_table.php, database/seeds/LoanStructureSeeder.php
adicion de parametros de intervalos  por modalidad BD
=> adicion de parametros de intervalos  por modalidad BD

app/Http/Controllers/Api/V1/CalculatorController.php, app/Rules/LoanIntervalAmount.php, app/Rules/LoanIntervalTerm.php, storage/responses/affiliate/get_loan_modality.200.json
Modificacion del metodo de la calculadora  nuevos intervalos
=> Modificacion del metodo de la calculadora  nuevos intervalos

app/Http/Controllers/Api/V1/AffiliateController.php, app/Http/Controllers/Api/V1/CalculatorController.php, storage/responses/affiliate/affiliate_evaluate_loans.200.json
Modificacion del metodo para pre evaluacion
=> Modificacion del metodo para pre evaluacion

database/seeds/AdvanceRoleSeeder.php, database/seeds/LoanPermissionSeeder.php
Adicion de permisos para calificacion y recepcion para los calculos y  requisitos deocumentos
=> Adicion de permisos para calificacion y recepcion

app/Http/Controllers/Api/V1/LoanController.php, routes/api.php
ajuste del metodo edit_amounts_loan_term
=> ajuste del metodo edit_amounts_loan_term

app/Affiliate.php, app/Http/Controllers/Api/V1/LoanController.php, routes/api.php, storage/responses/loan/update_sismu.200.json
adicion de ruta para actualizar sismu
=> adicion de ruta para actualizar sismu

app/Http/Controllers/Api/V1/CalculatorController.php, database/seeds/PaymentTypeSeeder.php
Quitar del seeder contabilidad
=> Quitar del seeder contabilidad

database/seeds/AdvanceRoleSeeder.php, database/seeds/LoanPermissionSeeder.php
creación del permiso actualizar saldo de refinanciamiento en el seeder
=> creación del permiso actualizar saldo de refinanciamiento en el seeder

database/seeds/ObservationTypeSeeder.php, version-seeder.sh
creación del Seeder ObservationTypeSeeder.php para observaciones del tramite
=> creación del Seeder ObservationTypeSeeder.php para observaciones del tramite

app/Http/Controllers/Api/V1/LoanController.php, database/seeds/AdvanceRoleSeeder.php, database/seeds/LoanPermissionSeeder.php
Adicion de permisos para editar personal de referencia y codeudor
=> Adicion de permisos para editar personal de referencia y codeudor

app/Http/Controllers/Api/V1/AffiliateController.php, app/Observers/SismuObserver.php, app/Providers/AppServiceProvider.php, app/Providers/SismuServiceProvider.php, app/Record.php, app/Sismu.php, config/app.php, database/seeds/AdvanceRoleSeeder.php, storage/responses/module/get_modality_types.200.json
Creacion de observadores del sismu
=> Creacion de observadores del sismu 

app/Http/Controllers/Api/V1/LoanController.php
colocar etiquetas de refi y repro solo a pos pvt
=> colocar etiquetas de refi y repro solo a pos pvt

app/Http/Controllers/Api/V1/AffiliateController.php, app/Http/Controllers/Api/V1/CalculatorController.php, app/Http/Controllers/Api/V1/LoanController.php, app/Loan.php, database/seeds/LoanPermissionSeeder.php
=> modalidades pestamos cambios

app/Http/Requests/LoanPaymentForm.php
=> Quitar validacion

composer.lock
=> Composer lock

app/Http/Controllers/Api/V1/LoanController.php
reporte excel del listado de prestamos
=> reporte excel del listado de prestamos 

app/Http/Controllers/Api/V1/LoanController.php, storage/responses/loan/show.200.json
=> añadir informacion  del loan

app/Http/Controllers/Api/V1/LoanController.php, resources/views/loan/payments/payment_plan.blade.php
Desembolso en efectivo para adicionar firmas
=> Desembolso en efectivo para adicionar firmas

app/Affiliate.php, app/Http/Requests/AffiliateForm.php
=>  afiliateForm

app/Loan.php
Arreglo de obtencion de modalidad en caso cpop LP
=> Arreglo de obtencion de modalidad en caso cpop LP

app/Http/Controllers/Api/V1/AffiliateController.php
=> Litado afiliados modificacion

app/Http/Controllers/Api/V1/AffiliateController.php
Cambio de valdaciones de garantes
=> Cambio de valdaciones de garantes

app/Http/Controllers/Api/V1/LoanController.php
Envio de second name en lista generate
=> Envio de second name en lista generate

resources/assets/js/components/payment/AddAmortization.vue
=> Se cambio el nombre de la descripción en la amortización  para los pendientes por confirmar

app/Http/Controllers/Api/V1/LoanPaymentController.php, config/translations.php
Correccion de la exportacion e importacion de pagos
=> Correccion de la exportacion e importacion de pagos

app/Affiliate.php, app/Http/Controllers/Api/V1/LoanController.php, app/Http/Controllers/Api/V1/LoanPaymentController.php, app/Http/Controllers/Api/V1/VoucherController.php, app/Http/Requests/VoucherForm.php, app/Spouse.php, app/Voucher.php, database/factories/LoanFactory.php, database/migrations/2020_07_21_094005_add_data_to_vouchers.php, database/seeds/LoanStateSeeder.php
Modificacion de cambio de estados y arreglo del voucher
=> Modificacion de cambio de estados y arreglo del voucher

app/Affiliate.php, app/Http/Controllers/Api/V1/LoanPaymentController.php, app/LoanPayment.php, resources/views/loan/payments/payment_kardex.blade.php, resources/views/loan/payments/payment_kardex_unfolded.blade.php
modificacion de loanpayment y kardex
=> modificacion de loanpayment y kardex

app/Http/Controllers/Api/V1/LoanPaymentController.php
=> Voucher confirmacion

app/Http/Controllers/Api/V1/LoanController.php
=> Adicion de info en el loan

resources/views/loan/forms/request_form.blade.php
adicion del numero de cuenta en el el form solicitud
=> adicion del numero de cuenta en el el form solicitud para cierre de ticket

app/Http/Controllers/Api/V1/LoanPaymentController.php, resources/views/loan/forms/request_form.blade.php
adicion del numero de cuenta en el el form solicitud
=> Adicion de informacion del domicilio en el form de solicitud

resources/views/loan/contracts/long.blade.php
adicion del numero de cuenta en el el form solicitud
=> Correccion bug de contrato largo plazo

app/Http/Controllers/Api/V1/LoanController.php
=> listado de prestamos vigentes

app/Http/Controllers/Api/V1/AffiliateController.php, app/Loan.php
Validadcion de modalidades repetidas
=> VAlidadcion de modalidades repetidas

app/Helpers/Util.php, resources/views/loan/contracts/advance.blade.php, resources/views/loan/contracts/short.blade.php
Modificación de contratos de anticipos y cortos
=> Modificación de contratos de anticipos y cortos

resources/assets/js/components/loan/Guarantor.vue
=> se realizo la modificación de los métodos de garante 

resources/views/loan/contracts/advance.blade.php, resources/views/loan/contracts/hypothecary.blade.php, resources/views/loan/contracts/long.blade.php, resources/views/loan/contracts/short.blade.php, resources/views/loan/forms/request_form.blade.php, resources/views/loan/payments/payment_kardex.blade.php, resources/views/loan/payments/payment_kardex_unfolded.blade.php
Contratos cambio de fecha al imprimible y adición de info al Form de solicitud y modifi de formato kardex
=> Contratos cambio de fecha al imprimible y adicion de info al Form de solicitud y modifi de formato kardex

resources/views/loan/contracts/short.blade.php
=> Arreglo de bug contrat

app/Http/Controllers/Api/V1/ImportationController.php, routes/api.php
metodo para descargar el archivo de descarga
=> metodo para descargar el archivo de descarga

database/migrations/2021_05_31_175359_create_loan_payment_group_commands_table.php, database/migrations/2021_06_23_095026_create_loan_payment_group_senasirs_table.php
Cambio de nombre de las migraciones y tablas
=> Cambio de nombre de las migraciones y tablas

app/Http/Controllers/Api/V1/ImportationController.php, routes/api.php
=> creación de método para visualizar barra de progreso pasos de importación

app/Http/Controllers/Api/V1/ImportationController.php, storage/responses/loan_payment/import_progress_bar.200.json
=> Ajuste en el metodo import_progress_bar para agregar periodo de importacion

app/Http/Controllers/Api/V1/LoanReportController.php
=> modificación del reporte de prestamos amortizados mensualmente descuento por garantía

resources/views/loan/forms/qualification_form.blade.php
=> se modifica de visulizacion de prestatarios que tengan a sus sposuse registrado

resources/assets/js/components/payment/AddAmortization.vue, resources/assets/js/components/payment/ImportExportPayment.vue, resources/assets/js/components/payment/Steps.vue
Formulario de cobros manuales. Cada vez que se realiza algún cambio en los campos de entrada se deberá presionar el botón calcular. 
Importación. Agregando loadings y habilitación  a los botones de descarga e importación.
=> Formulario de cobros manuales e importación.

resources/assets/js/components/dashboard/DataLoanInformation.vue, resources/assets/js/components/dashboard/Index.vue
Dashboard. Prestamos garantizados.Agregando las columnas titular,ci y matricula.
=> Dashboard. Agregando las columnas titular, ci y matricula 

app/Http/Controllers/Api/V1/AffiliateController.php
mejora para visualizar las fotos
=> visualizar la foto en la ventana de cargar fotografias
